project:
  type: book
  output-dir: docs

book:
  title: "CASA 0023 Remote Sensing Learning Diary"
  author: "Mengyu Ding"
  date: "2024-02-01"
  chapters:
    - index.qmd
    - intro.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week5.qmd
    - week6.qmd
    - week7.qmd
    - week8.qmd
    - week9.qmd
    - week10.qmd
    - summary.qmd
    - rs_acronym.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

