project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 Remote Sensing \n Learning Diary"
  author: "[Mengyu Ding](https://github.com/dereksgithub)"
  date: "2024-02-01"
  sidebar: 
    title: "CASA0023 Learning Diary Mengyu"
    style: floating
    collapse-level: 1
  chapters:
    - index.qmd
    - intro.qmd
    - part: "I. Intro to Remote Sensing"
      chapters: 
        - week1.qmd
        - week2.qmd
        - week3.qmd
        - week4.qmd
        - week5.qmd
    - part: "II. Remote Sensing with GEE"
      chapters:
      - week6.qmd
      - week7.qmd
      - week8.qmd
      - week9.qmd
    - week10.qmd
    - summary.qmd
    - rs_acronym.qmd
    - references.qmd
  repo-url: https://github.com/dereksgithub/learning_0023
  repo-actions: [edit, issue]
  favicon: images/favicon.png
  reader-mode: true
  
  
bibliography: references.bib

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    linkcolor: "#5785C1"
    code-copy: true
    code-overflow: wrap
    highlight-style: monokai.theme
    
  pdf:
    documentclass: scrreprt

editor: visual

