# Acronyms and Key Concepts in Remote Sensing {.unnumbered}

AOI: Area of Interest

ARVI: [Atmospherically Resistant Vegetation Index](week3.qmd)

AVHRR: [Advanced Very High Resolution Radiometer](https://en.wikipedia.org/wiki/Advanced_very-high-resolution_radiometer)

Azimuth: This is the [angle between a reference direction and the line between the observer/sensor and a specific point of interest on the ground](https://support.esri.com/en-us/gis-dictionary/azimuth).

CART:

DEM/DSM/DTM: [Digital Elevation Model](https://www.usgs.gov/faqs/what-digital-elevation-model-dem) / Digital Surface Model / Digital Terrain Model. This [article](https://geodetics.com/dem-dsm-dtm-digital-elevation-models/) and explains well the differences between DEM, DTM and DSM.

EO: Earth Observation

EOS: [Earth Observing System](https://eospso.nasa.gov/content/nasas-earth-observing-system-project-science-office)

ESA: [European Space Agency](https://www.esa.int/)

EVI: [Enhanced Vegetation Index](week3.qmd)

GIS: [Geographic Information System](https://www.usgs.gov/faqs/what-geographic-information-system-gis)

GAUL: Global Administrative Unit Layer:

GLCM: Gray-Level Co-occurrence Matrix. [This lecture note](https://web.pdx.edu/~jduh/courses/Archive/geog481w07/Students/Hayes_GreyScaleCoOccurrenceMatrix.pdf) is really helpful in understanding the details of GLCM.

GNDVI: [Green Normalized Difference Vegetation Index](week3.qmd)

GOES: [Geostationary Operational Environmental Satellite](https://science.nasa.gov/mission/goes/)

GSO: Geosynchronous Orbit, this is an orbit where, from the observer's (directly on the ground below the point of the object in orbit) reference frame, the object in orbit is stationary. [More detailed explanation is found here.](https://science.nasa.gov/learn/basics-of-space-flight/chapter5-1/)

IFOV: Instantaneous Field of View. Refers to the area on the ground, that a sensor in orbit can see and measure whenever it is ordered to.

LandSat: [Land Satellite](https://en.wikipedia.org/wiki/Landsat_program), more details on deciding which Landsat collection to import [see here](https://calekochenour.github.io/remote-sensing-textbook/01-catalog/chapter01-landsat.html).

LiDAR: [Light Detection and Ranging](https://en.wikipedia.org/wiki/Lidar)

LULC: Land Use and Land Cover

MODIS: Moderate Resolution Imaging Spectroradiometer

MSAVI: [Modified Soil-Adjusted Vegetation Index](week3.qmd)

NDMI: [Normalized Difference Moisture Index.](week3.qmd)

NDVI: [Normalized Difference Vegetation Index](week3.qmd)

NDWI: [Normalized Difference Water Index](week3.qmd)

NOAA: [National Oceanic and Atmospheric Administration](https://oceanservice.noaa.gov/about/)

PCA: Principal Component Analysis, a statistical technique used to reduce data dimensionality, prioritising significant features by transforming correlated bands into uncorrelated components.

POI: Point of Interest

RF: Random Forest

ROI: Region of Interest

SAVI: [Soil-Adjusted Vegetation Index](week3.qmd)

SNAP: [Sentinel Application Platform](https://step.esa.int/main/toolboxes/snap/), a software platform used for processing and analyzing satellite data, mostly European Space Agency's Sentinel series Earth Observation data.

SVM: [Support Vector Machine](https://www.youtube.com/watch?v=efR1C6CvhmE)

UAV: Unmanned Aerial Vehicle
