# Week 4 Remote Sensing and Policy Implications {.unnumbered}

Remote Sensing and Policy Implication goes hand-in-hand in order to address some of our most urgent challenges. The UN SDG has set out many goals for urban built-environments to meet. In this sense, my case of integrating the remote sensing monitoring of wildfires to provide urban air quality forecasts to provide the policy makers and city councils ample amount of time before the smogs hit the residential areas. Offering a potential policy integration which includes, edistributing air filtering systems, masks or vacuating affected population.

## Case Study of Wildfire Monitoring for Air Quality Interventions in Melbourne

Forecast bush fires in areas that may impact the residents. Focusing on Melbourne with Methodology derived from [@maclachlan2017urban]

<iframe width="530" height="300" src="https://www.youtube.com/embed/CqNhaan26t8?si=M27xHFCWYwcrPdx4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>

</iframe>

Utilizing[@trinder2020] the Sentinel 5P data, I plan in this study to design a

| Area of Research                                                          | Global Agenda | Methods                   | Data                              |
|-----------------------|---------------|---------------|---------------|
| Melbourne urban growth, provide forecasting advice for population growth. | UN SDG        | Using Remote Sensing Data | Combine the local councils' plans |
|                                                                           |               |                           |                                   |
|                                                                           |               |                           |                                   |
|                                                                           |               |                           |                                   |
|                                                                           |               |                           |                                   |

Using remote sensing for monitoring wild fire monitoring has long been proposed for Eastern Australia. [@milne1986use]

Using satellite imagery such as Sentinel 5p, monitor the wildfire and combined with ground weather monitoring data, to determine, for each year, how the polluted air will impact the densely populated area, thus provide intervention implications for distributing devices and masks.

Insert some 5P images around Melbourne

Set up high-feqy sentinel points, forecasting POIs for early air quality alerts prior to polluted air moving near the city area.

set up stations for storing filtering devices/resporitory devices for smokes, and relocation planning for emergency evacuation in case the air gets too smoky.

For emergency planning, techniques oncludes, ABM methods, and identifying routes via satellite images.
